$on_ac_power = systemd-ac-power
# $kbd_backlight = tpacpi::kbd_backlight


general {
	lock_cmd = pidof hyprlock || hyprlock
	before_sleep_cmd = loginctl lock-session
	after_sleep_cmd = hyprctl dispatch dpms on
}

### Dim screen ###############################################

# AC: dim screen to 10% after 5 min idle
listener {
	timeout = 300
	on-timeout = brightnessctl -s set 10
	on-resume = brightnessctl -r
}

### Keyboard backlight ###############################################

# # AC: turn off keyboard backlight after 10 min idle
# listener {
# 	timeout = $min10
# 	on-timeout = $on_ac_power && brightnessctl -sd $kbd_backlight set 0
# 	on-resume = brightnessctl -rd $kbd_backlight
# }

# # Battery: turn off keyboard backlight after 5 min idle
# listener {
# 	timeout = $min5
# 	on-timeout = $on_ac_power || brightnessctl -sd $kbd_backlight set 0
# 	on-resume = brightnessctl -rd $kbd_backlight
# }

## Display off ###############################################

# AC: turn off display after 10 min idle
listener {
    timeout = 600
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

### lock session ###############################################

# # AC: lock session after 15 min idle
# listener {
# 	timeout = 900
# 	on-timeout = $on_ac_power && lock_cmd
# }

### Sleep ###############################################

# # AC: suspend after 30 min idle
# listener {
# 	timeout = 1800
# 	on-timeout = $on_ac_power && systemctl suspend
# }
